variables:
  IMAGE_TAG: "2021-09-28-1"
  YOCTO_IMAGE: "amlogic-image-headless-initrd"
  MACHINE_NAME: "amlogic-s9xxx"
  IMAGE_NAME: "uImage"
  IMAGE_TYPE: "uimage"
  RAMDISK_COMP: "xz"

stages:
  - docker
  - initrd

build:docker:
  stage: docker
  tags: 
    - yocto
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$IMAGE_TAG && exit 0 || true
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG --tag $CI_REGISTRY_IMAGE:latest scripts/
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

build:initrd:
  tags: 
    - yocto
  stage: initrd
  image: $CI_REGISTRY_IMAGE:$IMAGE_TAG
  
  before_script:
    - mkdir -p results
    - rm -rf /tmp/build_env
    - git clone http://github.com/openembedded/openembedded-core --branch=mickledore --depth=1 /tmp/build_env
    - git clone http://github.com/openembedded/bitbake --branch=2.4 --depth=1 /tmp/build_env/bitbake
    - git clone $(pwd) /tmp/build_env/$(basename $(pwd))

  script:
    - bash scripts/prepare.sh /tmp/build_env
    - bash scripts/build.sh /tmp/build_env $MACHINE_NAME $YOCTO_IMAGE
    - cp -ar /tmp/build_env/build/tmp*/deploy/images/$MACHINE_NAME/* $CI_PROJECT_DIR/results/

  artifacts:
    when: always
    paths:
      - results/
