on:
  schedule:
    - cron: 0 8 * * 0

jobs:
  master:
    uses: ndechesne/meta-qcom/.github/workflows/build-template.yml@master
    with:
      host: ubuntu-20.04
      images: core-image-base core-image-weston core-image-x11 amlogic-image-bootstrap amlogic-image-headless-initrd amlogic-image-headless-sd amlogic-image-sato
      machines: amlogic-p200 amlogic-p200-sdboot amlogic-p201-sdboot amlogic-p212 amlogic-p212-sdboot amlogic-s400 friendlyelec-nanopik2 hardkernel-odroidc2 hardkernel-odroidc2-sdboot hardkernel-odroidc4 hardkernel-odroidc4-sdboot hardkernel-odroidhc4 hardkernel-odroidhc4-sdboot hardkernel-odroidn2 hardkernel-odroidn2-sdboot hardkernel-odroidn2plus hardkernel-odroidn2plus-sdboot khadas-vim khadas-vim-sdboot khadas-vim2 khadas-vim3 khadas-vim3-sdboot khadas-vim3l khadas-vim3l-sdboot libretech-ac libretech-cc radxa-zero seirobotics-sei510 seirobotics-sei610 
      ref_type: branch
      ref: master
      branch: master
      url: ${{github.server_url}}/${{github.repository}}
    secrets:
      TUXSUITE_TOKEN: ${{ secrets.TUXSUITE_TOKEN }}

  kirkstone:
    uses: ndechesne/meta-qcom/.github/workflows/build-template.yml@master
    with:
      host: ubuntu-20.04
      images: core-image-base core-image-weston core-image-x11 amlogic-image-bootstrap amlogic-image-headless-initrd amlogic-image-headless-sd amlogic-image-sato
      machines: amlogic-p200 amlogic-p200-sdboot amlogic-p201-sdboot amlogic-p212 amlogic-p212-sdboot amlogic-s400 friendlyelec-nanopik2 hardkernel-odroidc2 hardkernel-odroidc2-sdboot hardkernel-odroidc4 hardkernel-odroidc4-sdboot hardkernel-odroidhc4 hardkernel-odroidhc4-sdboot hardkernel-odroidn2 hardkernel-odroidn2-sdboot hardkernel-odroidn2plus hardkernel-odroidn2plus-sdboot khadas-vim khadas-vim-sdboot khadas-vim2 khadas-vim3 khadas-vim3-sdboot khadas-vim3l khadas-vim3l-sdboot libretech-ac libretech-cc radxa-zero seirobotics-sei510 seirobotics-sei610 
      ref_type: branch
      ref: kirkstone
      branch: kirkstone
      url: ${{github.server_url}}/${{github.repository}}
    secrets:
      TUXSUITE_TOKEN: ${{ secrets.TUXSUITE_TOKEN }}

  dunfell:
    uses: ndechesne/meta-qcom/.github/workflows/build-template.yml@master
    with:
      host: ubuntu-20.04
      images: core-image-base core-image-weston core-image-x11 amlogic-image-bootstrap amlogic-image-headless-initrd amlogic-image-headless-sd amlogic-image-sato
      machines: amlogic-p200 amlogic-p200-sdboot amlogic-p201-sdboot amlogic-p212 amlogic-p212-sdboot amlogic-s400 friendlyelec-nanopik2 hardkernel-odroidc2 hardkernel-odroidc2-sdboot hardkernel-odroidc4 hardkernel-odroidc4-sdboot hardkernel-odroidhc4 hardkernel-odroidhc4-sdboot hardkernel-odroidn2 hardkernel-odroidn2-sdboot hardkernel-odroidn2plus hardkernel-odroidn2plus-sdboot khadas-vim khadas-vim-sdboot khadas-vim2 khadas-vim3 khadas-vim3-sdboot khadas-vim3l khadas-vim3l-sdboot libretech-ac libretech-cc seirobotics-sei510 seirobotics-sei610 
      ref_type: branch
      ref: dunfell
      branch: dunfell
      url: ${{github.server_url}}/${{github.repository}}
    secrets:
      TUXSUITE_TOKEN: ${{ secrets.TUXSUITE_TOKEN }}
